version: 2

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          name: Restore Cache
          key: node_modules-{{ .Branch }}-{{ checksum "./package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Set up to gas clasp enviroment.
          command: npm install
      - save_cache:
          name: Save Cache
          key: node_modules-{{ .Branch }}-{{ checksum "./package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run Build outgoing module
          command: npm run build_outgoing
      - run:
          name: Deploy outgoing module
          command: |
            if [ ${CIRCLE_BRANCH} = "master" ]; then
              echo $CLASPRC_JSON_PRODUCTION > ~/.clasprc.json
              echo $CLASP_JSON_OUTGOING_PRODUCTION > .clasp.json
              npx @google/clasp push
            elif [ ${CIRCLE_BRANCH} = "develop" ]; then
              echo $CLASPRC_JSON_TEST > ~/.clasprc.json
              echo $CLASP_JSON_OUTGOING_TEST > .clasp.json
              npx @google/clasp push
            else
              echo "${CIRCLE_BRANCH} isn't deploy branch."
            fi
      - run:
          name: Run Build slashcommand module
          command: npm run build_slashcommand
      - run:
          name: Deploy slashcommand module
          command: |
            if [ ${CIRCLE_BRANCH} = "master" ]; then
              echo $CLASPRC_JSON_PRODUCTION > ~/.clasprc.json
              echo $CLASP_JSON_SLASHCOMMAND_PRODUCTION > .clasp.json
              npx @google/clasp push
            elif [ ${CIRCLE_BRANCH} = "develop" ]; then
              echo $CLASPRC_JSON_TEST > ~/.clasprc.json
              echo $CLASP_JSON_SLASHCOMMAND_TEST > .clasp.json
              npx @google/clasp push
            else
              echo "${CIRCLE_BRANCH} isn't deploy branch."
            fi

workflows:
  version: 2
  on_deploy_branches:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: 
                - master
                - develop